src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_DateTime__c</fullName>
        <label>Error Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Exception_Handler.cls
/*********************************************************************************
Class Name      : Exception_Handler 
Description     : Utility class for handling exceptions.
*/

public with sharing class Exception_Handler 
{
    /*********************************************************************************
    Method Name     : handleException
    Description     : utility method to handle all the caught exceptions in catch block.
    Return Type     : Void
    Parameters      : exception object, Additional information on exception..
    *********************************************************************************/
    public static void handleException(Exception e, String Message) {        
        Error_Log__c errLog = new Error_Log__c( Error_Datetime__c= DateTime.Now(),
                                                Error_Message__c= e.getMessage(),
                                                Running_User__c = UserInfo.getUserId() ,
                                                Stack_Trace__c = e.getStackTraceString(),
                                                Additional_Information__c = Message                                                               
                                              );                       
        insert errLog ;
    }
}